RGR_fruit_ini = 0.0105          # initial relative growth rate of fruit [dd-1]
cc_fruit = 0.4239               # carbon content of fruit dry matter [g C g-1 DM]
GRC_fruit = 0.04                # growth respiration coefficient of fruit [g C g-1 DM]
