dd_thresh = nan
sucrose_ripe_thresh = 0.04      # threshold sucrose content in the flesh beyond which fruit is assumed ripe [g g-1 FM]

e_fruitDM2FM_1 = 23.647         # specific parameter for fruit fresh mass calculation based on fruit dry mass (for fruits with L < 105 mm) [g1-0,6182 DM]
e_fruitDM2FM_2 = 0.6182         # specific parameter for fruit fresh mass calculation based on fruit dry mass (for fruits with L < 105 mm) [dimensionless]
e_fruit2peelW_1 = 0.4086	    # specific parameter for fruit peel water mass calculation based on fruit water mass [g1-0,7428 H20]
e_fruit2peelW_2 = 0.7428	    # specific parameter for fruit peel water mass calculation based on fruit water mass [dimensionless]
e_fruit2fleshW_1 = 0.5874	    # specific parameter for fruit flesh water mass calculation based on fruit water mass [g1-1,0584 H2O]
e_fruit2fleshW_2 = 1.0584	    # specific parameter for fruit flesh water mass calculation based on fruit water mass [dimensionless]

h = 0.002027                    # coeffcient of "cell wall hardening" [MPa cm-3]
phi_max = 0.414                 # maximal cell wall extensibility [MPa-1 day-1]
tau = 0.966                     # rate of decrease in cell wall extensibility [dimensionless]
aLf = 0.3732                    # product of the ratio of the area of the vascular network to the fruit area (a) by the hydraulic conductivity between the stem and the fruit for water transport (Lf)  [g H2O cm-2 MPa-1 day-1]
osmotic_pressure_aa = 0.2       # osmotic pressure in fruit flesh due to amino acids [MPa]
ro = 5544                       # fruit surface conductance [cm day-1]
RH_fruit = 0.996                # relative humidity of air space in fruit [dimensionless]
Y_0 = 0                         # threshold pressure at full bloom beyond which growth could occur [MPa]
V_0 = 0                         # fruit flesh volume at full bloom [cm3]
psat_1 = 0.008048               # specific parameter for saturation vapor pressure calculation based on air temperature [bar]
psat_2 = 0.0547                 # specific parameter for saturation vapor pressure calculation based on air temperature [°C-1]
density_DM = 1.6                # density of dry matter [g cm-3]
e_fruit2peelDM_1 = 0.4086       # specific parameter for fruit peel dry mass calculation based on fruit dry mass [g1-0.7641 DM]
e_fruit2peelDM_2 = 0.7641       # specific parameter for fruit peel dry mass calculation based on fruit dry mass [dimensionless]
e_fruit2fleshDM_1 = 0.5219      # specific parameter for fruit flesh dry mass calculation based on fruit dry mass [g1-1.0584 DM]
e_fruit2fleshDM_2 = 1.0584      # specific parameter for fruit flesh dry mass calculation based on fruit dry mass [dimensionless]
e_fleshpeel2fleshDM = 0.8226    # proportion of flesh in fruit flesh and peel dry mass [dimensionless]
e_fleshpeel2fleshW = 0.8958     # proportion of flesh in fruit flesh and peel water mass [dimensionless]
e_fruitFM2surface_1 = 3.65      # specific parameter for fruit surface calculation based on fruit fresh mass [cm2 g-0.73 FM]
e_fruitFM2surface_2 = 0.73      # specific parameter for fruit surface calculation based on fruit fresh mass [dimensionless]
e_flesh2stoneFM = 0.1167        # ratio of fruit stone fresh mass to fruit flesh and peel fresh mass [dimensionless]
swp_1 = -0.6617105              # specific parameter for stem water potential calculation based on air temperature, air relative humidity and global radiation [MPa]
swp_2 = -0.006940179            # specific parameter for stem water potential calculation based on air temperature, air relative humidity and global radiation [MPa °C-1]
swp_3 = 0.007888208             # specific parameter for stem water potential calculation based on air temperature, air relative humidity and global radiation [MPa]
swp_4 = 0.0000198265            # specific parameter for stem water potential calculation based on air temperature, air relative humidity and global radiation [MPa J-1 cm2 h]
ddthres_1 = 20.769              # specific paramater for cell wall degree-days threshold calculation based on fruit dry mass at the end of cell division [dd g-1 DM]
ddthres_2 = 518.87              # specific paramater for cell wall degree-days threshold calculation based on fruit dry mass at the end of cell division [dd]

[delta]  # specific parameters for calculation of mass proportion of malic acid in fruit flesh based on degree-days and fruit flesh dry mass [g g-1 DM] [g g-1 DM dd-1] [g g-2 DM] [g g-2 DM dd-1] :
mal = [ 0.06620651,  -0.0000538797,  -0.002464413,    2.406565e-06]   # malic acid
cit = [ 0.1625024,   -0.0000640754,   0.003906348,   -4.784292e-06]   # citric acid
pyr = [ 0.0006896104, 1.613387e-06,   0.00005063595, -6.912509e-08]   # pyruvic acid
oxa = [ 0.004750718, -2.113094e-06,  -0.00002965687,  0.0]            # oxalic acid
K =   [ 0.01394964,  -5.234608e-06,  -0.000288464,    2.682089e-07]   # K+
Mg =  [ 0.00115595,  -7.937479e-07,  -0.00002320017,  2.344528e-08]   # Mg2+
Ca =  [ 0.001588606, -6.625787e-07,  -0.0000228527,   1.514343e-08]   # Ca2+
NH4 = [ 0.000246011,  3.741743e-07,   0.00002495255, -3.010081e-08]   # NH4+
Na =  [ 0.0001279568, 8.15203e-08,   -1.468235e-06,   0.0]            # Na+
glc = [ 0.08074145,  -0.00006325543, -0.001161846,    1.161344e-06]   # glucose
frc = [ 0.04972199,   0.0000966001,  -0.001078579,    0.0]            # fructose
suc = [ 0.0,          0.00017695,    -0.007249,       9.03e-06]       # sucrose
sta = [-0.1708815,    0.0004380411,   0.01923022,    -0.00002059459]  # starch
