fruitDM0_weight_1 = 0.97        # specific parameter for fruit dry mass distribution at the end of cell division [dimensionless]
fruitDM0_mu_1 = 13.9	          # specific parameter for fruit dry mass distribution at the end of cell division [g DM]
fruitDM0_sigma_1 = 4.1          # specific parameter for fruit dry mass distribution at the end of cell division [g DM]
fruitDM0_weight_2 = 0.03        # specific parameter for fruit dry mass distribution at the end of cell division [dimensionless]
fruitDM0_mu_2 = 29.2            # specific parameter for fruit dry mass distribution at the end of cell division [g DM]
fruitDM0_sigma_2 = 0.66         # specific parameter for fruit dry mass distribution at the end of cell division [g DM]

e_fruitDM02max_1 = 16.736       # specific parameter for maximum fruit dry mass calculation [g1-0.624]
e_fruitDM02max_2 = 0.624        # specific parameter for maximum fruit dry mass calculation [dimensionless]

RGR_fruit_ini = 0.0105          # initial relative growth rate of fruit [dd-1]
cc_fruit = 0.4239               # carbon content of fruit dry matter [g C g-1 DM]
GRC_fruit = 0.04                # growth respiration coefficient of fruit [g C g-1 DM]

Tbase_fruit = 16                # base temperature for degree-days calculation [°C]
dd_cum_0 = 352.72               # cumulated degree-days at the end of cell division [dd]
