phyllotaxy = 144
t_ip_gu_mean = 1
t_ip_gu_sd = 89.4
t_ip_leaf = 91.02
# Tbase_gu = 9.2
# Tbase_leaf = 10.73
final_diameter = 0.2

pheno_angle_values = [0, 90, 165, 60, 60]

# GUs length
# Depends on Position. 3 Distributions are found. Apical Gu on Apical parent, Apical Gu on Lateral parent and Lateral GU.
# Mean and Std dev of length distribution.
gu_length_distrib = [
    [['apical',  'lateral'], [18.14 , 4.14]],
    [['apical',   'apical'], [13.79 , 4.03]],
    [['lateral',  'apical'], [12.59 , 3.38]],
    [['lateral', 'lateral'], [12.59 , 3.38]]
]

# Number of leafs
# Depends on Position and GU's length
# Ratio and intercept for the relation with leaf nb and length.
[leaf_nb_distrib]
apical = [0.59, 5.5]
lateral = [0.62, 0.36]

# Leaves length
# Depends on Position
# Mean and Std dev of length distribution.
[leaf_length_distrib]
apical = [17.06 , 2.7]
lateral = [14.87 , 2.7]

leaf_area_length_ratio = 2.3594
leaf_width_length_ratio = 0.24
radius_exponent = 0.443
radius_coefficient = 0.415
branching_angle = 60
max_leafy_diameter = 1.65
LEPF_distrib_apical = [2.007, 0.763]
LEPF_distrib_lateral = [0.38, 0.88]
B_gu = 22.41891079963771
maxGR_leaf = [-0.0188725, 0.0147985]
