name: vmango-lab
channels:
  - fredboudon
  - conda-forge
dependencies:
  - alinea.caribu
  - openalea.lpy>=3.6.0
  - openalea.mtg
  - xarray-simlab
  - jupyterlab<3.0.0
  - ipython=7
  - toml
  - matplotlib
  - pandas
  - igraph
  - sparse
  - scipy
  - pip
  - pip:
    - pgljupyter
