name: vmango-lab
channels:
  - fredboudon
  - conda-forge
dependencies:
  - alinea.caribu
  - openalea.lpy>=3.6.0
  - openalea.mtg
  - xarray-simlab>=0.5.0
  - jupyterlab
  - jupyterlab_widgets
  - ipython=7
  - toml
  - matplotlib
  - numpy>=1.20
  - pandas
  - python-igraph
  - sparse
  - scipy
  - flake8
  - pip
  - pip:
    - pgljupyter
