name: vmango-lab
channels:
  - fredboudon
  - conda-forge
dependencies:
  - alinea.caribu
  - openalea.lpy=3.8.*
  - openalea.plantgl=3.9.*
  - xarray-simlab=0.5.*
  - jupyterlab>=3.0.*
  - jupyterlab_widgets
  - ipython=7
  - toml
  - matplotlib
  - numpy=1.20.*
  - pandas
  - seaborn
  - sparse
  - scipy
  - pycairo
  - netCDF4
  - flake8
  - pip
  - pip:
    - pgljupyter>=1.1.*
    - python-igraph>=0.9.*
