name: vmango-lab
channels:
  - fredboudon
  - conda-forge
dependencies:
  - alinea.caribu
  - openalea.lpy=3.*
  - openalea.plantgl=3.*
  - openalea.mtg
  - xarray-simlab=0.5.*
  - jupyterlab=3.*
  - jupyterlab_widgets
  - ipython=7
  - toml
  - matplotlib
  - numpy=1.20.*
  - pandas
  - seaborn
  - sparse
  - scipy
  - pycairo
  - flake8
  - pip
  - pip:
    - pgljupyter>=1.0.3
    - python-igraph>=0.9.1
