title = 'fruit model branch'

# all paths must be relative to this file and name must match process name in model
[parameters]
topology = '../parameters/topology.toml'
environment = '../parameters/environment.toml'
phenology = '../parameters/phenology.toml'
growth = '../parameters/growth.toml'
appearance = '../parameters/growth.toml'
carbon_allocation = '../parameters/carbon_allocation.toml'
carbon_flow_coef = '../parameters/carbon_flow_coef.toml'
carbon_reserve = '../parameters/carbon_reserve.toml'
carbon_demand = '../parameters/carbon_demand.toml'
light_interception = '../parameters/light_interception.toml'
photosynthesis = '../parameters/photosynthesis.toml'
fruit_composition = '../parameters/fruit_composition.toml'
fruit_quality = '../parameters/fruit_quality.toml'
harvest = '../parameters/harvest.toml'
geometry = '../parameters/geometry.toml'
