title = 'fruit model'

# all paths must be relative to this file and name must match process name in model
[parameters]
environment = '../parameters/environment.toml'
phenology = '../parameters/phenology.toml'
growth = '../parameters/growth.toml'
appearance = '../parameters/growth.toml'
carbon_allocation = '../parameters/carbon_allocation.toml'
carbon_balance = '../parameters/carbon_balance.toml'
carbon_reserve = '../parameters/carbon_reserve.toml'
carbon_demand = '../parameters/carbon_demand.toml'
light_interception = '../parameters/light_interception.toml'
photosynthesis = '../parameters/photosynthesis.toml'
fruit_quality = '../parameters/fruit_quality.toml'
harvest = '../parameters/harvest.toml'
