title = 'vmango'

initial_tree = '../trees/tree_B10_cycle_030405.csv'

[parameters]
environment = '../parameters/environment.toml'
phenology = '../parameters/phenology.toml'
growth = '../parameters/growth.toml'
appearance = '../parameters/growth.toml'
arch_dev_veg_within = '../parameters/arch_dev_veg_within.toml'
arch_dev_veg_between = '../parameters/arch_dev_veg_between.toml'
arch_dev_rep = '../parameters/arch_dev_rep.toml'
arch_dev_mix = '../parameters/arch_dev_mix.toml'
carbon_allocation = '../parameters/carbon_allocation.toml'
carbon_balance = '../parameters/carbon_balance.toml'
carbon_reserve = '../parameters/carbon_reserve.toml'
carbon_demand = '../parameters/carbon_demand.toml'
light_interception = '../parameters/light_interception.toml'
photosynthesis = '../parameters/photosynthesis.toml'
fruit_quality = '../parameters/fruit_quality.toml'
harvest = '../parameters/harvest.toml'
