title = 'vmango'

[parameters]
environment = '../parameters/environment_vmango.toml'
phenology = '../parameters/phenology.toml'
growth = '../parameters/growth.toml'
appearance = '../parameters/growth.toml'
arch_dev_veg_within = '../parameters/arch_dev_veg_within.toml'
arch_dev_veg_between = '../parameters/arch_dev_veg_between.toml'
arch_dev_rep = '../parameters/arch_dev_rep.toml'
arch_dev_mix = '../parameters/arch_dev_mix.toml'
