title = 'dafault'

[parameters]
architecture = '../parameters/architecture.toml'
carbon_balance = '../parameters/carbon_balance.toml'
environment = '../parameters/environment.toml'
fruit_growth = '../parameters/fruit_growth.toml'
fruit_quality = '../parameters/fruit_quality.toml'
light_interception = '../parameters/light_interception.toml'
photosynthesis = '../parameters/photosynthesis.toml'
