channels:
  - fredboudon
  - conda-forge
dependencies:
  - alinea.caribu
  - openalea.lpy=3.8.*
  - openalea.plantgl=3.9.*
  - openalea.mtg
  - xarray-simlab=0.5.*
  - toml
  - matplotlib
  - numpy=1.20.*
  - pandas
  - seaborn
  - sparse
  - scipy
  - pycairo
  - netCDF4
  - pip
  - pip:
    - pgljupyter>=2.0.*
    - python-igraph>=0.9.*
