name: vmango-lab
channels:
  - fredboudon
  - conda-forge
dependencies:
  - python=3.10
  - openalea.lpy>=3.9
  - openalea.plantgl>=3.14
  - openalea.mtg
  - xarray-simlab=0.5
  - jupyterlab=4.0
  - ipywidgets=8.0
  - toml
  - matplotlib
  - numpy=1.22
  - pandas=2.1
  - seaborn
  - sparse
  - scipy=1.10
  - pycairo
  - netCDF4
  - python-igraph=0.11
  - pip
  - pip:
    - pgljupyter==2.0
    - -e ..
