name: vmango-lab
channels:
  - fredboudon
  - conda-forge
dependencies:
  - python=3.9.*
  - alinea.caribu
  - openalea.lpy=3.9.*
  - openalea.mtg
  - xarray-simlab=0.5.*
  - jupyterlab>=3.6.*
  - jupyterlab_widgets
  - ipywidgets
  - ipython=7
  - toml
  - matplotlib
  - numpy=1.20.*
  - pandas
  - seaborn
  - sparse
  - scipy=1.10.*
  - pycairo
  - netCDF4
  - pip
  - pip:
    - pgljupyter==2.0
    - python-igraph==0.9
    - -e ..
