name: vmango-lab
channels:
  - fredboudon
  - conda-forge
dependencies:
  - python=3.9
  - openalea.lpy=3.9
  - openalea.mtg
  - xarray-simlab=0.5
  - jupyterlab=3.6
  - jupyterlab_widgets=3.0
  - ipywidgets=8.0
  - ipython=7
  - toml
  - matplotlib
  - numpy
  - pandas
  - seaborn
  - sparse
  - scipy=1.10
  - pycairo
  - netCDF4
  - pip
  - pip:
    - pgljupyter==2.0
    - python-igraph==0.9
    - -e ..
