channels:
  - fredboudon
  - conda-forge
dependencies:
  - alinea.caribu
  - openalea.lpy=3.*
  - openalea.plantgl=3.*
  - openalea.mtg
  - xarray-simlab=0.5.*
  - toml
  - matplotlib
  - numpy=1.20.*
  - pandas
  - seaborn
  - sparse
  - scipy
  - pycairo
  - netCDF4
  - pip
  - pip:
    - pgljupyter>=1.0.5
    - python-igraph>=0.9.1
